import { TopOfferedGame } from "@/types"

export const topOfferedGames: TopOfferedGame[] = [
  {
    kind: "topOfferedGame",
    id: Math.random(),
    title: "Ratchet & Clank: Rift Apart",
    imageCover: "ratchet-and-clank-rift-apart.jpg",
    slug: "ratchet-and-clank-rift-apart",
    platform: { name: "PlayStation 5", slug: "ps5" },
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    kind: "topOfferedGame",
    id: Math.random(),
    title: "God of War",
    imageCover: "god-of-war.jpg",
    slug: "god-of-war",
    platform: { name: "PlayStation 4", slug: "ps4" },
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    kind: "topOfferedGame",
    id: Math.random(),
    title: "Returnal",
    imageCover: "returnal.jpg",
    slug: "returnal",
    platform: { name: "PlayStation 5", slug: "ps5" },
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    kind: "topOfferedGame",
    id: Math.random(),
    title: "God Of War: Ragnarök",
    imageCover: "god-of-war-ragnarok.jpg",
    slug: "god-of-war-ragnarok",
    platform: { name: "PlayStation 5", slug: "ps5" },
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    kind: "topOfferedGame",
    id: Math.random(),
    title: "Astro Bot",
    imageCover: "astro-bot.jpg",
    slug: "astro-bot",
    platform: { name: "PlayStation 5", slug: "ps5" },
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    kind: "topOfferedGame",
    id: Math.random(),
    title: "Ratchet & Clank: Rift Apart",
    imageCover: "ratchet-and-clank-rift-apart.jpg",
    slug: "ratchet-and-clank-rift-apart",
    platform: { name: "PlayStation 5", slug: "ps5" },
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
]
