export const game = {
  title: "Elden Ring",
  description: "Elden Ring certamente se provou o jogo mais ambicioso da FromSoftware e removeu qualquer preocupação de mudanças drásticas. Tudo que foi adicionado vem para acrescentar e enaltecer o que a empresa faz de melhor. O escopo maior da experiência é um presente e um deleite aos fãs, que ficarão felizes em saber que há mais conteúdo e de maior qualidade.",
  slug: "elden-ring",
  platformSlug: "ps5",
  platformName: "Playstation 5",
  genre: "RPG",
  rating: 4,
  urlOfficialSite: "https://www.bandainamcoent.com",
  studio: "From Software",
  distributor: "Bandai Namco Games",
  ratingEsbr: null,
  urlVideo: "uxwdq9G8DCo",
  releasedOn: "2022-02-25T03:00:00Z",
  imageCover: "elden-ring.jpg",
  wishes: 303,
  wishes30days: 6,
  offers: 193,
  offers30days: 3,
  urlIgn: "https://www.ign.com/games/elden-ring",
  urlMetacritic: "https://www.metacritic.com/game/playstation-5/elden-ring",
  urlGamespot: "https://www.gamespot.com/games/elden-ring/",
  scoreIgn: 0,
  scoreGamespot: 0,
  scoreMetacritic: 0,
  scoreMandaJogo: 9.5,
  isCollection: false,
  isExchanging: false,
  isWishlist: false
}
