export const gameOwners = {
  data: [
    {
      id: "clx3c5d6e7f8g9h0i1j2k3l4",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "Rafael",
      username: "aryhoo",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/rafael.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 6,
      enumLevelDesc: null,
      conditionMedia: 4,
      conditionMediaDesc: null,
      conditionBooklet: 5,
      conditionBookletDesc: null,
      conditionBox: 5,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Vitória",
      state: "ES",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3l5",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "Breno",
      username: "brsalomon",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/breno.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 5,
      enumLevelDesc: null,
      conditionMedia: 4,
      conditionMediaDesc: null,
      conditionBooklet: 4,
      conditionBookletDesc: null,
      conditionBox: 4,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Belo Horizonte",
      state: "MG",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3l6",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "Ricardo",
      username: "ricamehlitz",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/ricardo.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 4,
      enumLevelDesc: null,
      conditionMedia: 4,
      conditionMediaDesc: null,
      conditionBooklet: 3,
      conditionBookletDesc: null,
      conditionBox: 3,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3l7",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "Mario",
      username: "marioventura",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/mario.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 3,
      enumLevelDesc: null,
      conditionMedia: 2,
      conditionMediaDesc: null,
      conditionBooklet: 1,
      conditionBookletDesc: null,
      conditionBox: 2,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Rio de Janeiro",
      state: "RJ",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3l8",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "Arthur",
      username: "arthurhrc",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/arthur.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Lagoa da Prata",
      state: "MG",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3l9",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "Raffael",
      username: "raffapappa",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/raffael.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3la",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "Lamartine X",
      username: "lamartine_x_adriana_vidal_gomes",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/lamartine.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Bernardo do Campo",
      state: "SP",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3lb",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "André",
      username: "dedeapollo",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/andre.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3lc",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "Lucas",
      username: "bereman20",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/lucas.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
    },
    {
      id: "clx3c5d6e7f8g9h0i1j2k3ld",
      createdAt: "2025-06-02T00:00:00.000Z",
      name: "William",
      username: "will.pinhe",
      imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/william.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Ibitinga",
      state: "SP",
    },
  ],
  page: 1,
  totalUsers: 98
}
