export const gameProposal = {
  // id: "clx1c4d6e7f3g9h0i1j2k3l9",
  // createdAt: "2025-06-06T00:00:00.000Z",
  name: "Rafael",
  username: "aryhoo",
  imageAvatar: "https://raw.githubusercontent.com/Roger-Melo/mandajogo.com.br/refs/heads/main/public/users/game-owners/rafael.jpg",
  isVerified: false,
  gameTitle: "Elden Ring", // supplyName
  imageCover: "elden-ring.jpg",
  slug: "elden-ring",
  platformSlug: "ps5",
  scoreGeneral: 10,
  exchangesCount: 0,
  enumLevel: 6,
  enumLevelDesc: "Quero trocar de qualquer jeito",
  conditionMedia: 4,
  conditionMediaDesc: "Nenhum risco ou marcas de dedos",
  conditionBooklet: 5,
  conditionBookletDesc: "Nenhum arranhão ou marcas de dedos",
  conditionBox: 5,
  conditionBoxDesc: "Nenhum risco ou trincas",
  enumVersion: 1,
  enumVersionDesc: "Normal",
  enumRegion: 1,
  enumRegionDesc: "América (R1)",
  notes: null,
  city: "Vitória",
  state: "ES",
}
