export const topDesiredGames = [
  {
    id: Math.random(),
    title: "Elden Ring",
    imageCover: "elden-ring.jpg",
    slug: "elden-ring",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 193,
    wishes: 303,
    rating: 9.5,
  },
  {
    id: Math.random(),
    title: "Astro Bot",
    imageCover: "astro-bot.jpg",
    slug: "astro-bot",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 30,
    wishes: 70,
    rating: 9.3,
  },
  {
    id: Math.random(),
    title: "Spider-Man 2",
    imageCover: "spider-man-2.jpg",
    slug: "spider-man-2",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 30,
    wishes: 70,
    rating: 9.3,
  },
  {
    id: Math.random(),
    title: "Stellar Blade",
    imageCover: "stellar-blade.jpg",
    slug: "stellar-blade",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 30,
    wishes: 70,
    rating: 9.3,
  },
  {
    id: Math.random(),
    title: "Cyberpunk 2077: Ultimate Edition",
    imageCover: "cyberpunk-2077-ultimate-edition.jpg",
    slug: "cyberpunk-2077-ultimate-edition",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 30,
    wishes: 70,
    rating: 8.6,
  },
  {
    id: Math.random(),
    title: "The Last of Us Part II Remastered",
    imageCover: "the-last-of-us-part-ii-remastered.jpg",
    slug: "the-last-of-us-part-ii-remastered",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 134,
    wishes: 249,
    rating: 9.3,
  },
]

export const topOfferedGames = [
  {
    id: Math.random(),
    title: "Ratchet & Clank: Rift Apart",
    imageCover: "ratchet-and-clank-rift-apart.jpg",
    slug: "ratchet-and-clank-rift-apart",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    id: Math.random(),
    title: "God of War",
    imageCover: "god-of-war.jpg",
    slug: "god-of-war",
    platform: { name: "PlayStation 4", slug: "ps4" },
    description: null,
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    id: Math.random(),
    title: "Returnal",
    imageCover: "returnal.jpg",
    slug: "returnal",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    id: Math.random(),
    title: "God Of War: Ragnarök",
    imageCover: "god-of-war-ragnarok.jpg",
    slug: "god-of-war-ragnarok",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    id: Math.random(),
    title: "Astro Bot",
    imageCover: "astro-bot.jpg",
    slug: "astro-bot",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
  {
    id: Math.random(),
    title: "Ratchet & Clank: Rift Apart",
    imageCover: "ratchet-and-clank-rift-apart.jpg",
    slug: "ratchet-and-clank-rift-apart",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 134,
    wishes: 249,
    rating: 8.8,
  },
]

export const newReleases = [
  {
    id: Math.random(),
    title: "Suikoden I & II HD Remaster Gate Rune and Dunan Unification Wars",
    imageCover: "stellar-blade.jpg",
    slug: "suikoden-i-and-ii-hd-remaster-gate-rune-and-dunan-unification-wars",
    releasedOn: "2025-05-30T03:00:00Z",
    platforms: [
      { name: "Playstation 5", slug: "ps5", company: "Sony" },
      { name: "Nintendo Switch", slug: "nintendo-switch", company: "Nintendo" },
    ],
    description: "Suikoden I & II HD Remaster: Clássicos RPGs Ganham Vida Nova no PS5!\n\nOs lendários jogos de RPG Suikoden I e II retornam com um remaster em HD, trazendo uma experiência visual e sonora totalmente revigorada. Gráficos e sons foram atualizados para proporcionar ao jogador um mergulho ainda mais profundo nas histórias épicas desses clássicos. Não perca a oportunidade de reviver essa aventura melhor do que nunca!",
  },
  {
    id: Math.random(),
    title: "Atomfall",
    imageCover: "god-of-war.jpg",
    slug: "atomfall",
    releasedOn: "2025-05-30T03:00:00Z",
    platforms: [
      { name: "Playstation 4", slug: "ps4", company: "Sony" },
      { name: "Playstation 5", slug: "ps5", company: "Sony" },
    ],
    description: "Prepare-se para uma jornada intensa em \"Atomfall\", onde suas escolhas serão cruciais em um cenário devastado por um desastre nuclear. Explore a tranquila, mas perigosa, paisagem do campo britânico e descubra os segredos ocultos dessa intrigante narrativa. Cada decisão pode mudar o rumo de sua sobrevivência!",
  },
  {
    id: Math.random(),
    title: "The First Berserker Khazan",
    imageCover: "astro-bot.jpg",
    slug: "the-first-berserker-khazan",
    releasedOn: "2025-05-30T03:00:00Z",
    platforms: [
      { name: "Playstation 5", slug: "ps5", company: "Sony" },
    ],
    description: "Mergulhe no Passado com Khazan: Aventure-se no Universo de DNF\n\nDesperte seu herói interior em \"The First Berserker: Khazan\". Reviva a história de Khazan e Ozma, os lendários salvadores do Império Pell Los. Acompanhe Khazan, o herói exilado, em sua busca por justiça após ser injustamente acusado de traição. Experimente um RPG de ação carregado de batalhas intensas e uma narrativa envolvente.",
  },
  {
    id: Math.random(),
    title: "Assassin's Creed Shadows",
    imageCover: "spider-man-2.jpg",
    slug: "assassins-creed-shadows",
    releasedOn: "2025-05-30T03:00:00Z",
    platforms: [
      { name: "Playstation 5", slug: "ps5", company: "Sony" },
    ],
    description: "Mergulhe no Japão Feudal: Uma Aventura Inesquecível em Terra de Samurais e Shinobis\n\nEntre no mundo vibrante do Japão Feudal e experimente uma aventura épica ao lado de Naoe, o assassino furtivo, e Yasuke, o icônico samurai. Explore paisagens impressionantes e absorva a mudança das estações enquanto desvenda a intrigante trama que une estes lendários guerreiros. Descubra um universo onde a tática e a ação se entrelaçam para criar uma experiência única.",
  },
  {
    id: Math.random(),
    title: "Monster Hunter Wilds",
    imageCover: "stellar-blade.jpg",
    slug: "monster-hunter-wilds",
    releasedOn: "2025-05-30T03:00:00Z",
    platforms: [
      { name: "Playstation 5", slug: "ps5", company: "Sony" },
    ],
    description: "Aventura Selvagem - Monster Hunter Wilds Leva os Jogadores para as Terras Proibidas",
  },
  {
    id: Math.random(),
    title: "Suikoden I & II HD Remaster Gate Rune and Dunan Unification Wars",
    imageCover: "stellar-blade.jpg",
    slug: "suikoden-i-and-ii-hd-remaster-gate-rune-and-dunan-unification-wars",
    releasedOn: "2025-05-30T03:00:00Z",
    platforms: [
      { name: "Playstation 5", slug: "ps5", company: "Sony" },
      { name: "Nintendo Switch", slug: "nintendo-switch", company: "Nintendo" },
    ],
    description: "Suikoden I & II HD Remaster: Clássicos RPGs Ganham Vida Nova no PS5!\n\nOs lendários jogos de RPG Suikoden I e II retornam com um remaster em HD, trazendo uma experiência visual e sonora totalmente revigorada. Gráficos e sons foram atualizados para proporcionar ao jogador um mergulho ainda mais profundo nas histórias épicas desses clássicos. Não perca a oportunidade de reviver essa aventura melhor do que nunca!",
  },
]

export const platforms = [
  { id: Math.random(), name: "Playstation 5", slug: "ps5", },
  { id: Math.random(), name: "Playstation 4", slug: "ps4", },
  { id: Math.random(), name: "XBOX One", slug: "xbox-one", },
  { id: Math.random(), name: "Nintendo Switch", slug: "nintendo-switch", },
  { id: Math.random(), name: "Wii U", slug: "wii-u", },
  { id: Math.random(), name: "Playstation 3", slug: "ps3", },
]

export const game = {
  title: "Elden Ring",
  description: "Elden Ring certamente se provou o jogo mais ambicioso da FromSoftware e removeu qualquer preocupação de mudanças drásticas. Tudo que foi adicionado vem para acrescentar e enaltecer o que a empresa faz de melhor. O escopo maior da experiência é um presente e um deleite aos fãs, que ficarão felizes em saber que há mais conteúdo e de maior qualidade.",
  slug: "elden-ring",
  platformSlug: "ps5",
  platformName: "Playstation 5",
  genre: "RPG",
  rating: 4,
  urlOfficialSite: "https://www.bandainamcoent.com",
  studio: "From Software",
  distributor: "Bandai Namco Games",
  ratingEsbr: null,
  urlVideo: "uxwdq9G8DCo",
  releasedOn: "2022-02-25T03:00:00Z",
  imageCover: "elden-ring.jpg",
  wishes: 303,
  wishes30days: 6,
  offers: 193,
  offers30days: 3,
  urlIgn: "https://www.ign.com/games/elden-ring",
  urlMetacritic: "https://www.metacritic.com/game/playstation-5/elden-ring",
  urlGamespot: "https://www.gamespot.com/games/elden-ring/",
  scoreIgn: 0,
  scoreGamespot: 0,
  scoreMetacritic: 0,
  scoreMandaJogo: 9.5,
  isCollection: false,
  isExchanging: false,
  isWishlist: false
}
