import { TopGame } from "@/types"

export const topDesiredGames: TopGame[] = [
  {
    id: Math.random(),
    title: "Elden Ring",
    imageCover: "elden-ring.jpg",
    slug: "elden-ring",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 193,
    wishes: 303,
    rating: 9.5,
  },
  {
    id: Math.random(),
    title: "Astro Bot",
    imageCover: "astro-bot.jpg",
    slug: "astro-bot",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 30,
    wishes: 70,
    rating: 9.3,
  },
  {
    id: Math.random(),
    title: "Spider-Man 2",
    imageCover: "spider-man-2.jpg",
    slug: "spider-man-2",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 30,
    wishes: 70,
    rating: 9.3,
  },
  {
    id: Math.random(),
    title: "Stellar Blade",
    imageCover: "stellar-blade.jpg",
    slug: "stellar-blade",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 30,
    wishes: 70,
    rating: 9.3,
  },
  {
    id: Math.random(),
    title: "Cyberpunk 2077: Ultimate Edition",
    imageCover: "cyberpunk-2077-ultimate-edition.jpg",
    slug: "cyberpunk-2077-ultimate-edition",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 30,
    wishes: 70,
    rating: 8.6,
  },
  {
    id: Math.random(),
    title: "The Last of Us Part II Remastered",
    imageCover: "the-last-of-us-part-ii-remastered.jpg",
    slug: "the-last-of-us-part-ii-remastered",
    platform: { name: "PlayStation 5", slug: "ps5" },
    description: null,
    offers: 134,
    wishes: 249,
    rating: 9.3,
  },
]
