export const gameOwners = {
  data: [
    {
      name: "Rafael",
      username: "aryhoo",
      imageAvatar: "rafael.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 6,
      enumLevelDesc: null,
      conditionMedia: 4,
      conditionMediaDesc: null,
      conditionBooklet: 5,
      conditionBookletDesc: null,
      conditionBox: 5,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Vitória",
      state: "ES",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Breno",
      username: "brsalomon",
      imageAvatar: "breno.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 5,
      enumLevelDesc: null,
      conditionMedia: 4,
      conditionMediaDesc: null,
      conditionBooklet: 4,
      conditionBookletDesc: null,
      conditionBox: 4,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Belo Horizonte",
      state: "MG",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Ricardo",
      username: "ricamehlitz",
      imageAvatar: "ricardo.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 4,
      enumLevelDesc: null,
      conditionMedia: 4,
      conditionMediaDesc: null,
      conditionBooklet: 3,
      conditionBookletDesc: null,
      conditionBox: 3,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Mario",
      username: "marioventura",
      imageAvatar: "mario.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 3,
      enumLevelDesc: null,
      conditionMedia: 2,
      conditionMediaDesc: null,
      conditionBooklet: 1,
      conditionBookletDesc: null,
      conditionBox: 2,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Rio de Janeiro",
      state: "RJ",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Arthur",
      username: "arthurhrc",
      imageAvatar: "arthur.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Lagoa da Prata",
      state: "MG",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Raffael",
      username: "raffapappa",
      imageAvatar: "raffael.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Lamartine X",
      username: "lamartine_x_adriana_vidal_gomes",
      imageAvatar: "lamartine.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Bernardo do Campo",
      state: "SP",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "André",
      username: "dedeapollo",
      imageAvatar: "andre.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Lucas",
      username: "bereman20",
      imageAvatar: "lucas.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "William",
      username: "will.pinhe",
      imageAvatar: "william.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 2,
      enumLevelDesc: null,
      conditionMedia: 3,
      conditionMediaDesc: null,
      conditionBooklet: 0,
      conditionBookletDesc: null,
      conditionBox: 1,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Ibitinga",
      state: "SP",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
  ],
  page: 1,
  totalUsers: 98
}
