export const gameOwners = {
  data: [
    {
      name: "Rafael",
      username: "aryhoo",
      imageAvatar: "rafael.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 5,
      enumLevelDesc: null,
      conditionMedia: 6,
      conditionMediaDesc: null,
      conditionBooklet: 6,
      conditionBookletDesc: null,
      conditionBox: 6,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Vitória",
      state: "ES",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Breno",
      username: "brsalomon",
      imageAvatar: "breno.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 5,
      enumLevelDesc: null,
      conditionMedia: 6,
      conditionMediaDesc: null,
      conditionBooklet: 6,
      conditionBookletDesc: null,
      conditionBox: 6,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Belo Horizonte",
      state: "MG",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Ricardo",
      username: "ricamehlitz",
      imageAvatar: "ricardo.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 5,
      enumLevelDesc: null,
      conditionMedia: 6,
      conditionMediaDesc: null,
      conditionBooklet: 6,
      conditionBookletDesc: null,
      conditionBox: 6,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "São Paulo",
      state: "SP",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Mario",
      username: "marioventura",
      imageAvatar: "mario.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 5,
      enumLevelDesc: null,
      conditionMedia: 6,
      conditionMediaDesc: null,
      conditionBooklet: 6,
      conditionBookletDesc: null,
      conditionBox: 6,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Rio de Janeiro",
      state: "RJ",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
    {
      name: "Arthur",
      username: "arthurhrc",
      imageAvatar: "arthur.jpg",
      isVerified: false,
      supplyName: null,
      imageCover: null,
      supplyPermalink: null,
      bundlePermalink: null,
      scoreGeneral: 0,
      exchangesCount: 0,
      enumLevel: 5,
      enumLevelDesc: null,
      conditionMedia: 6,
      conditionMediaDesc: null,
      conditionBooklet: 6,
      conditionBookletDesc: null,
      conditionBox: 6,
      conditionBoxDesc: null,
      enumVersion: 1,
      enumVersionDesc: null,
      enumRegion: 1,
      enumRegionDesc: null,
      notes: null,
      city: "Lagoa da Prata",
      state: "MG",
      distance: 0.0,
      lat: 0.0,
      lng: 0.0
    },
  ],
  page: 1,
  totalUsers: 98
}
